version: "3.7"
services:
  apollo-server:
    build:
      context: server
    command: npm run start
    ports:
      - "5000:5000"
  front-end:
    build:
      context: client
    command: npm run dev
    ports:
      - "3000:3000"
